DUI--DButtonList {
    background-color: grey;
}

DUI--DButtonList QFrame#BorderFrame{
  background-color: transparent;
}

DUI--DButtonList QFrame#BorderFrame[state="checked"]{
  background-color: transparent;
}

DUI--DButtonList QPushButton{
    background-color: transparent;
    color: white;
    border: none;
    border-radius:3px;
    text-align: left center;
    padding-left: 40;
}

DUI--DButtonList QPushButton:checked{
    background-color: lightblack;
}
