DUI--DCalendar #CalendarView {
    qproperty-backgroundCircleColor:#0064fa;
    qproperty-defaultTextColor:#eee;
    qproperty-defaultLunarColor:#eee;
    qproperty-festivalLunarColor:#01BDFF;
    qproperty-weekendsTextColor:#eee;
    qproperty-weekendsLunarColor:#eee;
}

DUI--DCalendar QLineEdit{
    border:none;
    background-color:transparent;
    color:white;
}

DUI--DCalendar QLabel{
    color:white;
}
