DUI--DCheckBox {
    spacing: 5px;
    color: #CCCCCC;
    font-size: 12px;
}

DUI--DCheckBox:hover {
    color: white;
}

DUI--DCheckBox::indicator:unchecked {
    image: url(:/images/dark/images/checkbox_unchecked.png);
}

DUI--DCheckBox::indicator:unchecked:hover {
    image: url(:/images/dark/images/checkbox_unchecked_hover.png);
}

DUI--DCheckBox::indicator:unchecked:pressed {
    image: url(:/images/dark/images/checkbox_unchecked_hover.png);
}

DUI--DCheckBox::indicator:unchecked:!enabled {
    image: url(:/images/dark/images/checkbox_unchecked_insensitive.png);
}

DUI--DCheckBox::indicator:checked {
    image: url(:/images/dark/images/checkbox_checked.png);
}

DUI--DCheckBox::indicator:checked:hover {
    image: url(:/images/dark/images/checkbox_checked_hover.png);
}

DUI--DCheckBox::indicator:checked:pressed {
    image: url(:/images/dark/images/checkbox_checked_hover.png);
}

DUI--DCheckBox::indicator:checked:!enabled {
    image: url(:/images/dark/images/checkbox_checked_insensitive.png);
}
