
DUI--DOption {
    margin:0 10px;
    padding:0 10px;
    qproperty-checkedIcon:url(:/images/dark/images/tick_transparent.png);
}

DUI--DOption[checked="true"] {
    background-color: lightblack;
    border-radius:3px;
    qproperty-checkedIcon:url(:/images/dark/images/tick_hover.png);
}

DUI--DOption #OptionName {
    color: #b4b4b4;
}

DUI--DOption #OptionName:hover {
    color: white;
}

DUI--DOption[checked="true"] #OptionName {
    color: #2ca7f8;
}
