DUI--DSlider::groove {
    background: yellow;
    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */
    left: 4px; right: 4px;
}

DUI--DSlider::handle {
    height: 10px;
    background: red;
    margin: 0 -4px; /* expand outside the groove */
}

DUI--DSlider::add-page {
    background: black;
}

DUI--DSlider::sub-page {
    background: cyan;
}
